INSERT INTO PRODUTO (NO_PRODUTO, IC_TIPO_PERFIL_RISCO, IC_TIPO_PRODUTO, PC_TAXA_ANUAL_OFERECIDA, NU_LIQUIDEZ_DIAS, NO_RISCO)
VALUES ('CDB Caixa', 0, 'CDB', 0.13, 1, 'Baixo');

INSERT INTO PRODUTO (NO_PRODUTO, IC_TIPO_PERFIL_RISCO, IC_TIPO_PRODUTO, PC_TAXA_ANUAL_OFERECIDA, NU_LIQUIDEZ_DIAS, NO_RISCO)
VALUES ('Fundo Agressivo XPTO', 2, 'Fundos', 0.18, 30, 'Alto');

INSERT INTO PRODUTO (NO_PRODUTO, IC_TIPO_PERFIL_RISCO, IC_TIPO_PRODUTO, PC_TAXA_ANUAL_OFERECIDA, NU_LIQUIDEZ_DIAS, NO_RISCO)
VALUES ('Tesouro Selic', 0, 'Tesouro Direto', 0.06, 1, 'Muito Baixo');

INSERT INTO PRODUTO (NO_PRODUTO, IC_TIPO_PERFIL_RISCO, IC_TIPO_PRODUTO, PC_TAXA_ANUAL_OFERECIDA, NU_LIQUIDEZ_DIAS, NO_RISCO)
VALUES ('Fundo Tech Growth', 2, 'Fundos', 0.22, 60, 'Muito Alto');

INSERT INTO PRODUTO (NO_PRODUTO, IC_TIPO_PERFIL_RISCO, IC_TIPO_PRODUTO, PC_TAXA_ANUAL_OFERECIDA, NU_LIQUIDEZ_DIAS, NO_RISCO)
VALUES ('Ações BlueChip', 2, 'Ações', 0.25, 1, 'Muito Alto');

INSERT INTO PRODUTO (NO_PRODUTO, IC_TIPO_PERFIL_RISCO, IC_TIPO_PRODUTO, PC_TAXA_ANUAL_OFERECIDA, NU_LIQUIDEZ_DIAS, NO_RISCO)
VALUES ('LCA Multimercado', 1, 'LCA', 0.12, 90, 'Medio');

INSERT INTO PRODUTO (NO_PRODUTO, IC_TIPO_PERFIL_RISCO, IC_TIPO_PRODUTO, PC_TAXA_ANUAL_OFERECIDA, NU_LIQUIDEZ_DIAS, NO_RISCO)
VALUES ('LCI Multimercado', 1, 'LCI', 0.13, 90, 'Medio');

INSERT INTO PRODUTO (NO_PRODUTO, IC_TIPO_PERFIL_RISCO, IC_TIPO_PRODUTO, PC_TAXA_ANUAL_OFERECIDA, NU_LIQUIDEZ_DIAS, NO_RISCO)
VALUES ('Fundo Viver de Renda', 2, 'Fundos', 0.17, 45, 'Alto');

INSERT INTO PRODUTO (NO_PRODUTO, IC_TIPO_PERFIL_RISCO, IC_TIPO_PRODUTO, PC_TAXA_ANUAL_OFERECIDA, NU_LIQUIDEZ_DIAS, NO_RISCO)
VALUES ('CDB Facil', 0, 'CDB', 0.11, 1, 'Baixo');

INSERT INTO PRODUTO (NO_PRODUTO, IC_TIPO_PERFIL_RISCO, IC_TIPO_PRODUTO, PC_TAXA_ANUAL_OFERECIDA, NU_LIQUIDEZ_DIAS, NO_RISCO)
VALUES ('Fundo Imobiliário', 0, 'Fundos', 0.08, 30, 'Muito Baixo');