INSERT INTO PRODUTO (NO_PRODUTO, IC_TIPO_PERFIL_RISCO, IC_TIPO_PRODUTO, PC_TAXA_ANUAL_OFERECIDA, NU_LIQUIDEZ_DIAS, PC_CUSTO_TRANSACAO, NU_VOLUME_MEDIO_DIARIO, NO_EMISSOR, NO_RATING, NO_RISCO)
VALUES ('CDB Caixa', 0, 'CDB', 0.13, 1, 0.001, 120000, 'Caixa Econômica Federal', 'AA', 'Baixo');

INSERT INTO PRODUTO (NO_PRODUTO, IC_TIPO_PERFIL_RISCO, IC_TIPO_PRODUTO, PC_TAXA_ANUAL_OFERECIDA, NU_LIQUIDEZ_DIAS, PC_CUSTO_TRANSACAO, NU_VOLUME_MEDIO_DIARIO, NO_EMISSOR, NO_RATING, NO_RISCO)
VALUES ('Fundo Agressivo XPTO', 2, 'Fundos', 0.18, 30, 0.002, 500000, 'Gestora XPTO', 'B', 'Alto');

INSERT INTO PRODUTO (NO_PRODUTO, IC_TIPO_PERFIL_RISCO, IC_TIPO_PRODUTO, PC_TAXA_ANUAL_OFERECIDA, NU_LIQUIDEZ_DIAS, PC_CUSTO_TRANSACAO, NU_VOLUME_MEDIO_DIARIO, NO_EMISSOR, NO_RATING, NO_RISCO)
VALUES ('Tesouro Selic', 0, 'Tesouro Direto', 0.06, 1, 0.0005, 8000000, 'Tesouro Nacional', 'AAA', 'Muito Baixo');

INSERT INTO PRODUTO (NO_PRODUTO, IC_TIPO_PERFIL_RISCO, IC_TIPO_PRODUTO, PC_TAXA_ANUAL_OFERECIDA, NU_LIQUIDEZ_DIAS, PC_CUSTO_TRANSACAO, NU_VOLUME_MEDIO_DIARIO, NO_EMISSOR, NO_RATING, NO_RISCO)
VALUES ('Fundo Tech Growth', 2, 'Fundos', 0.22, 60, 0.0025, 300000, 'Tech Asset Management', 'C', 'Muito Alto');

INSERT INTO PRODUTO (NO_PRODUTO, IC_TIPO_PERFIL_RISCO, IC_TIPO_PRODUTO, PC_TAXA_ANUAL_OFERECIDA, NU_LIQUIDEZ_DIAS, PC_CUSTO_TRANSACAO, NU_VOLUME_MEDIO_DIARIO, NO_EMISSOR, NO_RATING, NO_RISCO)
VALUES ('Ações BlueChip', 2, 'Ações', 0.25, 1, 0.003, 2000000, 'B3 S.A.', 'A', 'Muito Alto');

INSERT INTO PRODUTO (NO_PRODUTO, IC_TIPO_PERFIL_RISCO, IC_TIPO_PRODUTO, PC_TAXA_ANUAL_OFERECIDA, NU_LIQUIDEZ_DIAS, PC_CUSTO_TRANSACAO, NU_VOLUME_MEDIO_DIARIO, NO_EMISSOR, NO_RATING, NO_RISCO)
VALUES ('LCA Multimercado', 1, 'LCA', 0.12, 90, 0.001, 150000, 'Banco Multimercado', 'A', 'Medio');

INSERT INTO PRODUTO (NO_PRODUTO, IC_TIPO_PERFIL_RISCO, IC_TIPO_PRODUTO, PC_TAXA_ANUAL_OFERECIDA, NU_LIQUIDEZ_DIAS, PC_CUSTO_TRANSACAO, NU_VOLUME_MEDIO_DIARIO, NO_EMISSOR, NO_RATING, NO_RISCO)
VALUES ('LCI Multimercado', 1, 'LCI', 0.13, 90, 0.001, 180000, 'Banco Multimercado', 'A', 'Medio');

INSERT INTO PRODUTO (NO_PRODUTO, IC_TIPO_PERFIL_RISCO, IC_TIPO_PRODUTO, PC_TAXA_ANUAL_OFERECIDA, NU_LIQUIDEZ_DIAS, PC_CUSTO_TRANSACAO, NU_VOLUME_MEDIO_DIARIO, NO_EMISSOR, NO_RATING, NO_RISCO)
VALUES ('Fundo Viver de Renda', 2, 'Fundos', 0.17, 45, 0.002, 400000, 'Viver Asset', 'B', 'Alto');

INSERT INTO PRODUTO (NO_PRODUTO, IC_TIPO_PERFIL_RISCO, IC_TIPO_PRODUTO, PC_TAXA_ANUAL_OFERECIDA, NU_LIQUIDEZ_DIAS, PC_CUSTO_TRANSACAO, NU_VOLUME_MEDIO_DIARIO, NO_EMISSOR, NO_RATING, NO_RISCO)
VALUES ('CDB Facil', 0, 'CDB', 0.11, 1, 0.001, 100000, 'Banco Fácil', 'A', 'Baixo');

INSERT INTO PRODUTO (NO_PRODUTO, IC_TIPO_PERFIL_RISCO, IC_TIPO_PRODUTO, PC_TAXA_ANUAL_OFERECIDA, NU_LIQUIDEZ_DIAS, PC_CUSTO_TRANSACAO, NU_VOLUME_MEDIO_DIARIO, NO_EMISSOR, NO_RATING, NO_RISCO)
VALUES ('Fundo Imobiliário', 0, 'Fundos', 0.08, 30, 0.0015, 250000, 'Real Estate Fund', 'A', 'Muito Baixo');