INSERT INTO PRODUTO (NO_PRODUTO, IC_TIPO_PRODUTO, PC_TAXA_ANUAL_OFERECIDA, NU_LIQUIDEZ_DIAS, PC_CUSTO_TRANSACAO, NU_VOLUME_MEDIO_DIARIO, NO_EMISSOR, NO_RATING)
VALUES ('CDB Banco Inter', 'CDB', 0.132, 1, 0.001, 120000, 'Banco Inter', 'A');

INSERT INTO PRODUTO (NO_PRODUTO, IC_TIPO_PRODUTO, PC_TAXA_ANUAL_OFERECIDA, NU_LIQUIDEZ_DIAS, PC_CUSTO_TRANSACAO, NU_VOLUME_MEDIO_DIARIO, NO_EMISSOR, NO_RATING)
VALUES ('Tesouro Selic 2027', 'TESOURO', 0.1075, 1, 0.0005, 5000000, 'Tesouro Nacional', 'AAA');

INSERT INTO PRODUTO (NO_PRODUTO, IC_TIPO_PRODUTO, PC_TAXA_ANUAL_OFERECIDA, NU_LIQUIDEZ_DIAS, PC_CUSTO_TRANSACAO, NU_VOLUME_MEDIO_DIARIO, NO_EMISSOR, NO_RATING)
VALUES ('LCI Banco do Brasil', 'LCI', 0.098, 90, 0.001, 80000, 'Banco do Brasil', 'AA');